on:
    workflow_dispatch:
    push:
        branches: [ "**/main" ]
        paths: [ "**/src/**" ]

jobs:
    publish:
        uses: ApexStudios-Dev/.github/.github/workflows/publish-mod.yml@master
        secrets: inherit
        with:
            curseforge_id: "1194521"
            modrinth_id: "M29GVxmz"
            release_type: "alpha"
            name: "ApexCompatibilities"
            logo: "https://raw.githubusercontent.com/ApexStudios-Dev/.github/refs/heads/master/assets/minecraft/new/apexcompatibilities.png"
            color: "3948743" # 3C40C7
